name: Release

on:
    workflow_dispatch:

jobs:
    pypi:
        runs-on: ubuntu-latest

        steps:
            - name: Set up Python
              uses: actions/setup-python@v3
              with:
                  python-version: 3.12

            - name: Install dependencies
              run: |
                  python3 -m pip install --upgrade pip
                  pip install -r requirements-dev.txt
                  python3 -m pip install --upgrade build

            - name: Build package
              run: python3 -m build

            - name: Install twine
              run: python3 -m pip install --upgrade twine

            - name: Check package
              run: twine check dist/*

            - name: Upload to PyPI
              env:
                  TWINE_USERNAME: __token__
                  TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
              run: |
                  python3 -m twine upload dist/*
