name: Unittests
on: [pull_request]

jobs:
    Python_3_12:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - name: Set up Python 3.12
              uses: actions/setup-python@v1
              with:
                  python-version: 3.12
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  python -m pip install -r requirements.txt
            - name: Unittests
              working-directory: tests
              run: python start.py

    Python_3_8:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - name: Set up Python 3.8
              uses: actions/setup-python@v1
              with:
                  python-version: 3.8
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  python -m pip install -r requirements.txt
            - name: Unittests
              working-directory: tests
              run: python start.py

    Python_3_7:
        runs-on: uubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - name: Set up Python 3.7
              uses: actions/setup-python@v1
              with:
                  python-version: 3.7
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  python -m pip install -r requirements.txt
            - name: Unittests
              working-directory: tests
              run: python start.py

    Python_3_6:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - name: Set up Python 3.6
              uses: actions/setup-python@v1
              with:
                  python-version: 3.6
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  python -m pip install -r requirements.txt
            - name: Unittests
              working-directory: tests
              run: python start.py
